version: 1.0.0.{build}
image: Visual Studio 2015

configuration: Release
platform: x86

before_build:
- ps: >-
    Write-Host "`tDownload CoD4x"

    Write-Host $pwd

    cd ../

    curl -o CoD4x_Server-17.7.2.tar.gz https://codeload.github.com/callofduty4x/CoD4x_Server/tar.gz/v17.7.2

    7z x CoD4x_Server-17.7.2.tar.gz | Out-Null

    7z x CoD4x_Server-17.7.2.tar | Out-Null

    Write-Host "`tInstalling pexports"

    curl -o pexports-0.47-mingw32-bin.tar.xz https://github.com/callofduty4x/CoD4x_Server/raw/master/tools/pexports-0.47-mingw32-bin.tar.xz

    7z x pexports-0.47-mingw32-bin.tar.xz | Out-Null

    7z x pexports-0.47-mingw32-bin.tar -o"CoD4x_Server-17.7.2" | Out-Null

    Write-Host "`tInstalling NASM"

    curl -o nasm-2.14rc15-win32.zip https://www.nasm.us/pub/nasm/releasebuilds/2.14rc15/win32/nasm-2.14rc15-win32.zip

    7z x nasm-2.14rc15-win32.zip -o"nasm" | Out-Null

    Write-Host "`tSetting up environment variables"
    
    [Environment]::SetEnvironmentVariable("PATH",  "C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;$pwd\CoD4x_Server-17.7.2\bin;$pwd\nasm\nasm-2.14rc15;$($env:path)")

    Write-Host "`tMoving CGSC to cod4x source directory"

    move cgsc ./CoD4x_Server-17.7.2/src/cgsc

    ls

    nasm -v

build_script:
- ps: >-
    Write-Host "`tBuilding CoD4x with CGSC"

    cd CoD4x_Server-17.7.2

    curl -o makefile https://iswenzz.com:1337/github/cgsc/makefile

    mingw32-make.exe

    ls