name: Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        sudo apt-get install g++-multilib gcc-multilib
        sudo dpkg --add-architecture i386
        sudo apt-get install nasm:i386 paxctl:i386 libtommath-dev:i386

    - name: CoD4x
      run: |
        cd ../
        curl -o CoD4x_Server-17.7.2.tar.gz https://codeload.github.com/callofduty4x/CoD4x_Server/tar.gz/v17.7.2
        7z x CoD4x_Server-17.7.2.tar.gz
        7z x CoD4x_Server-17.7.2.tar
        curl -o ./CoD4x_Server-17.7.2/makefile https://iswenzz.com:1337/github/CGSC/makefile
        ls
        mv cgsc ./CoD4x_Server-17.7.2/src/cgsc

    - name: Build
      run: |
        cd ../CoD4x_Server-17.7.2
        make
