name: Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies
      run: |
        sudo apt-get install g++-multilib gcc-multilib
        sudo dpkg --add-architecture i386
        sudo apt-get install nasm:i386 paxctl:i386 libtommath-dev:i386

    - name: Build
      run: |
        mkdir build && cd build
        conan install .. --build missing --profile ../.conan/linux.conf -o enable_testing=True
        cmake .. -DENABLE_TESTING=True
        cmake --build .

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build

  tests:
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build

    - name: Tests
      working-directory: build
      run: |
        ctest -C Release
